# -*- coding: utf-8 -*-
"""chatbot_code_using_transformer_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iZmP6scp52-cx2ZMrvDhGdoc9u5jhF11
"""

!pip install transformers langchain torch gradio langchain_classic

"""#import libraries"""

import torch
import gradio as gr



from transformers import AutoModelForCausalLM, AutoTokenizer


import warnings
warnings.filterwarnings("ignore")

#model for training & tokenization
model_name ="meta-llama/Llama-2-7b-chat-hf"
#model_name = "NousResearch/Llama-2-7b-chat-hf"
token=""

# Check if CUDA is available and move model to GPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

from huggingface_hub import login
login(token="")   # your new token

model_name = "meta-llama/Llama-2-7b-chat-hf"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name).to(device)



#tokenizer = AutoTokenizer.from_pretrained(model_name)
#model = AutoModelForCausalLM.from_pretrained(model_name).to(device)

def chatbot_response(user_input):
    # input(text) converted to vectors
    inputs = tokenizer(user_input, return_tensors="pt", max_length=512, truncation=True).to(device)

    # model gives o/p vectors
    outputs = model.generate(**inputs)
    #output vectors should be converted to text
    bot_reply = tokenizer.decode(outputs[0], skip_special_tokens=True)

    if bot_reply.startswith(user_input):
      bot_reply = bot_reply[len(user_input):].strip()

    return bot_reply

"""Gradio user interface"""

import gradio as gr

def chatbot_interface(user_input, history):
    response = chatbot_response(user_input)
    history.append((user_input, response))
    return history, ""

# Creating the Gradio Interface
demo = gr.Blocks()

with demo:
    gr.Markdown("## GenAI Chatbot")
    chatbot = gr.Chatbot()
    with gr.Row():
        user_input = gr.Textbox(placeholder="Type your message here...", lines=1)
        send_button = gr.Button("Send")

    history = gr.State([])

    send_button.click(chatbot_interface, inputs=[user_input, history], outputs=[chatbot, user_input])
    user_input.submit(chatbot_interface, inputs=[user_input, history], outputs=[chatbot, user_input])

demo.launch(share=True)

demo.close()